addSbtPlugin("com.geirsson"    % "sbt-scalafmt"           % "1.4.0")
addSbtPlugin("com.jsuereth"    % "sbt-pgp"                % "2.0.1")
addSbtPlugin("org.scalastyle"  %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"   % "sbt-scoverage"          % "1.6.1")
addSbtPlugin("org.xerial.sbt"  % "sbt-sonatype"           % "3.8")
addSbtPlugin("org.wartremover" % "sbt-wartremover"        % "2.4.5")
