addSbtPlugin("com.geirsson"     % "sbt-scalafmt"           % "1.4.0")
addSbtPlugin("org.scalastyle"   %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"          % "1.5.1")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph"   % "0.9.0")
addSbtPlugin("io.get-coursier"  % "sbt-coursier"           % "2.0.0-RC3-4")
addSbtPlugin("org.wartremover"  % "sbt-wartremover"        % "2.4.2")
