name: Continus Integration

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'master'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI
        run: |
          curl -u 607d69ecd9c49c334321f057f11918faab8e8064: -X POST --header "Content-Type: application/json" -d '{
            "branch": "${{ github.event.inputs.branch }}",
            "parameters": {
              "skip": false
            }
          }' https://circleci.com/api/v2/project/github/alephium/alephium-scala-common/pipeline

